spring:
  profiles: local
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3306/covid-tracker?useSSL=false
    username: root
    password: root
  cache:
    type: simple