spring:
  profiles: default
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL5Dialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://35.198.3.25:3306/dev-api
    username: root
    password: BksyncPbJsPycNEP
  cache:
    type: simple