spring:
  profiles: dev
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://b77b5f054fde14:3b1f492d@us-cdbr-east-02.cleardb.com/heroku_cac68a2130329c7?reconnect=true
    username: b77b5f054fde14:3b1f492d@us-cdbr-east-02.cleardb.com
    password: 3b1f492d
    tomcat:
      max-active: 9
      max-wait: 10000
      min-idle: 9
      test-on-borrow: true
      time-between-eviction-runs-millis: 300000
      max-idle: 9
      validation-query: select 1
      validation-interval: 30000
      test-while-idle: true
    hikari:
      maximum-pool-size: 9
      max-lifetime: 10000
  cache:
    type: simple